# Dockerfile.base
# Purpose: Build this ONCE. It contains all heavy dependencies.
FROM python:3.9-slim

WORKDIR /app

# System dep
# RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

# The heavy lift: Installs PyTorch, Transformers, LightGBM (2GB+)
RUN pip install --no-cache-dir -r requirements.txt
